name: Build and deploy client to GKE

on:
  push:
    branches:
      - master
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'client/**'

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-north1-a

  NAMESPACE_NAME: adm-4
  DEPLOYMENT_NAME: adm-client
  CONTAINER_NAME: adm-client
  IMAGE_NAME: docker.pkg.github.com/didream/adm-visualizacion-datos-iv/adm-client-4

  SECRET_GITHUB_REGISTRY: ${{ secrets.SECRET_GITHUB_REGISTRY }}

jobs:
  client_to_registry:
    name: Build and push Docker image to GitHub Packages and deploy to GKE
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          dockerfile: client/etc/Dockerfile
          path: client
          repository: didream/adm-visualizacion-datos-iv/adm-client-4
          tag_with_sha: true
          tags: ${{ github.sha }}

      - name: Setup gcloud CLI
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Get the GKE credentials
        run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE" --project "$PROJECT_ID"

      - name: Create k8s resources of app
        run: |-
          kubectl create -f etc/k8s/01-namespace.yml || true
          cat etc/k8s/02-github-package-secret.yml | sed "s/<SECRET_GITHUB_REGISTRY>/$SECRET_GITHUB_REGISTRY/" | kubectl apply -f - || true
          kubectl create -f client/etc/k8s || true

      - name: Update container image
        run: |-
          kubectl set image deployment/"$DEPLOYMENT_NAME" "$CONTAINER_NAME"="$IMAGE_NAME":"${{ github.sha }}" -n "$NAMESPACE_NAME"